const http = require('http');
const fs   = require('fs');
const path = require('path');
const url  = require('url');
const pool = require('./db');

// ============================================================
// 科目配置（加权随机分数范围）
// ============================================================
const SUBJECT_RANGES = {
  '语文':   [82, 120],
  '数学':   [78, 120],
  '英语':   [80, 120],
  '物理':   [65, 100],
  '化学':   [65, 100],
  '生物':   [62, 100],
  '历史':   [62, 100],
  '地理':   [62, 100],
  '思想政治': [60, 100]
};
const SUBJECTS = Object.keys(SUBJECT_RANGES);

// ============================================================
// 随机分数（正态分布近似，clamp 到区间）
// ============================================================
function randomScore(min, max) {
  const mid = (min + max) / 2;
  const sigma = (max - min) / 5;
  const u1 = Math.random(), u2 = Math.random();
  const z = Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
  return Math.max(min, Math.min(max, Math.round(mid + z * sigma)));
}

function generateScores() {
  const scores = {};
  for (const [sub, [min, max]] of Object.entries(SUBJECT_RANGES)) {
    scores[sub] = randomScore(min, max);
  }
  return scores;
}

// ============================================================
// DB 辅助：把数据库行转换成前端期望的格式
// ============================================================
function rowToStudent(row) {
  return {
    id:            row.id,
    name:          row.name,
    examId:        row.exam_id,
    school:        row.school,
    scores:        row.scores,
    autoGenerated: row.auto_generated,
    generatedAt:   row.generated_at
  };
}

// ============================================================
// HTTP 工具函数
// ============================================================
function readBody(req) {
  return new Promise(resolve => {
    let body = '';
    req.on('data', c => body += c);
    req.on('end', () => {
      try { resolve(JSON.parse(body)); } catch { resolve({}); }
    });
  });
}

function send(res, status, data) {
  res.writeHead(status, {
    'Content-Type': 'application/json; charset=utf-8',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type'
  });
  res.end(JSON.stringify(data));
}

function serveFile(res, filePath) {
  const ext = path.extname(filePath);
  const mime = ext === '.html' ? 'text/html' : 'text/plain';
  fs.readFile(filePath, (err, data) => {
    if (err) { res.writeHead(404); res.end('Not found'); return; }
    res.writeHead(200, { 'Content-Type': mime + '; charset=utf-8' });
    res.end(data);
  });
}

// ============================================================
// 路由
// ============================================================
const server = http.createServer(async (req, res) => {
  const parsed   = url.parse(req.url, true);
  const pathname = parsed.pathname;
  const method   = req.method;

  if (method === 'OPTIONS') { send(res, 200, {}); return; }

  // ---------- 静态页面 ----------
  if (method === 'GET' && pathname === '/') {
    serveFile(res, path.join(__dirname, 'public', 'index.html')); return;
  }
  if (method === 'GET' && pathname === '/result') {
    serveFile(res, path.join(__dirname, 'public', 'result.html')); return;
  }
  if (method === 'GET' && pathname === '/admin') {
    serveFile(res, path.join(__dirname, 'admin', 'index.html')); return;
  }

  // ---------- API: 前台查询 ----------
  if (method === 'GET' && pathname === '/api/query') {
    const { name, examId } = parsed.query;
    if (!name || !examId) { send(res, 400, { error: '请填写姓名和准考证号' }); return; }

    try {
      // 先查
      const { rows } = await pool.query(
        'SELECT * FROM students WHERE name = $1 AND exam_id = $2',
        [name.trim(), examId.trim()]
      );

      if (rows.length > 0) {
        send(res, 200, { success: true, student: rowToStudent(rows[0]) });
        return;
      }

      // 查不到 → 自动生成并写入
      const scores = generateScores();
      const now    = new Date().toISOString();
      const ins = await pool.query(
        `INSERT INTO students (name, exam_id, school, scores, auto_generated, generated_at)
         VALUES ($1, $2, $3, $4, true, $5)
         RETURNING *`,
        [name.trim(), examId.trim(), '浙江省教育考试院', JSON.stringify(scores), now]
      );
      console.log(`[自动生成] ${name.trim()} / ${examId.trim()}`);
      send(res, 200, { success: true, student: rowToStudent(ins.rows[0]) });

    } catch (e) {
      console.error('query error:', e.message);
      send(res, 500, { error: '数据库错误，请稍后重试' });
    }
    return;
  }

  // ---------- API: 后台获取所有考生 ----------
  if (method === 'GET' && pathname === '/api/admin/students') {
    try {
      const { rows } = await pool.query('SELECT * FROM students ORDER BY id ASC');
      send(res, 200, {
        students:      rows.map(rowToStudent),
        subjects:      SUBJECTS,
        subjectRanges: SUBJECT_RANGES
      });
    } catch (e) {
      console.error('list error:', e.message);
      send(res, 500, { error: '数据库错误' });
    }
    return;
  }

  // ---------- API: 新增考生 ----------
  if (method === 'POST' && pathname === '/api/admin/students') {
    const { name, examId, school, scores } = await readBody(req);
    if (!name || !examId || !school) {
      send(res, 400, { error: '姓名、准考证号、学校为必填项' }); return;
    }
    try {
      const { rows } = await pool.query(
        `INSERT INTO students (name, exam_id, school, scores)
         VALUES ($1, $2, $3, $4)
         RETURNING *`,
        [name, examId, school, JSON.stringify(scores || {})]
      );
      send(res, 201, { success: true, student: rowToStudent(rows[0]) });
    } catch (e) {
      if (e.code === '23505') { send(res, 400, { error: '准考证号已存在' }); }
      else { console.error('insert error:', e.message); send(res, 500, { error: '数据库错误' }); }
    }
    return;
  }

  // ---------- API: 更新考生 ----------
  if (method === 'PUT' && pathname.startsWith('/api/admin/students/')) {
    const id   = parseInt(pathname.split('/').pop());
    const body = await readBody(req);
    try {
      // 检查准考证号冲突
      if (body.examId) {
        const chk = await pool.query(
          'SELECT id FROM students WHERE exam_id = $1 AND id != $2', [body.examId, id]
        );
        if (chk.rows.length) { send(res, 400, { error: '准考证号已被其他考生使用' }); return; }
      }
      const { rows } = await pool.query(
        `UPDATE students
         SET name = COALESCE($1, name),
             exam_id = COALESCE($2, exam_id),
             school  = COALESCE($3, school),
             scores  = COALESCE($4, scores),
             auto_generated = false,
             updated_at = now()
         WHERE id = $5
         RETURNING *`,
        [body.name || null, body.examId || null, body.school || null,
         body.scores ? JSON.stringify(body.scores) : null, id]
      );
      if (!rows.length) { send(res, 404, { error: '考生不存在' }); return; }
      send(res, 200, { success: true, student: rowToStudent(rows[0]) });
    } catch (e) {
      console.error('update error:', e.message);
      send(res, 500, { error: '数据库错误' });
    }
    return;
  }

  // ---------- API: 删除考生 ----------
  if (method === 'DELETE' && pathname.startsWith('/api/admin/students/')) {
    const id = parseInt(pathname.split('/').pop());
    try {
      const { rowCount } = await pool.query('DELETE FROM students WHERE id = $1', [id]);
      if (!rowCount) { send(res, 404, { error: '考生不存在' }); return; }
      send(res, 200, { success: true });
    } catch (e) {
      console.error('delete error:', e.message);
      send(res, 500, { error: '数据库错误' });
    }
    return;
  }

  // ---------- API: 随机分数预览 ----------
  if (method === 'GET' && pathname === '/api/admin/preview-scores') {
    send(res, 200, { scores: generateScores() });
    return;
  }

  res.writeHead(404); res.end('Not found');
});

// ============================================================
// 启动
// ============================================================
const PORT = process.env.PORT || 3000;

async function start() {
  try {
    await pool.query('SELECT 1');   // 测试连接
    console.log('✅ 数据库连接成功');
  } catch (e) {
    console.error('❌ 数据库连接失败:', e.message);
    console.error('   请检查环境变量 DATABASE_URL 是否正确设置');
    process.exit(1);
  }
  server.listen(PORT, () => {
    console.log(`✅ 服务启动：http://localhost:${PORT}`);
    console.log(`   前台查询：http://localhost:${PORT}/`);
    console.log(`   后台管理：http://localhost:${PORT}/admin`);
  });
}

start();
