const http = require('http');
const fs   = require('fs');
const path = require('path');
const url  = require('url');
const pool = require('./db');

const SUBJECT_RANGES = {
  '语文':   [82, 120], '数学': [78, 120], '英语': [80, 120],
  '物理':   [65, 100], '化学': [65, 100], '生物': [62, 100],
  '历史':   [62, 100], '地理': [62, 100], '思想政治': [60, 100]
};
const SUBJECTS = Object.keys(SUBJECT_RANGES);

function randomScore(min, max) {
  const mid = (min + max) / 2, sigma = (max - min) / 5;
  const z = Math.sqrt(-2 * Math.log(Math.random())) * Math.cos(2 * Math.PI * Math.random());
  return Math.max(min, Math.min(max, Math.round(mid + z * sigma)));
}
function generateScores() {
  const s = {};
  for (const [sub, [min, max]] of Object.entries(SUBJECT_RANGES)) s[sub] = randomScore(min, max);
  return s;
}
function rowToStudent(row) {
  return { id: row.id, name: row.name, examId: row.exam_id, school: row.school,
           scores: row.scores, autoGenerated: row.auto_generated, generatedAt: row.generated_at };
}
function readBody(req) {
  return new Promise(resolve => {
    let body = '';
    req.on('data', c => body += c);
    req.on('end', () => { try { resolve(JSON.parse(body)); } catch { resolve({}); } });
  });
}
function send(res, status, data) {
  res.writeHead(status, {
    'Content-Type': 'application/json; charset=utf-8',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Cache-Control': 'no-store'
  });
  res.end(JSON.stringify(data));
}
function serveFile(res, filePath) {
  fs.readFile(filePath, (err, data) => {
    if (err) { res.writeHead(404); res.end('Not found'); return; }
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' });
    res.end(data);
  });
}

const server = http.createServer(async (req, res) => {
  const parsed = url.parse(req.url, true);
  const pathname = parsed.pathname;
  const method = req.method;

  if (method === 'OPTIONS') { send(res, 200, {}); return; }

  if (method === 'GET' && pathname === '/') { serveFile(res, path.join(__dirname, 'public', 'index.html')); return; }
  if (method === 'GET' && pathname === '/result') { serveFile(res, path.join(__dirname, 'public', 'result.html')); return; }
  if (method === 'GET' && pathname === '/admin') { serveFile(res, path.join(__dirname, 'admin', 'index.html')); return; }

  // 前台查询：只用姓名
  if (method === 'GET' && pathname === '/api/query') {
    const { name } = parsed.query;
    if (!name || !name.trim()) { send(res, 400, { error: '请填写姓名' }); return; }
    try {
      const { rows } = await pool.query('SELECT * FROM students WHERE name = $1', [name.trim()]);
      if (rows.length > 0) { send(res, 200, { success: true, student: rowToStudent(rows[0]) }); return; }

      // 自动生成，用随机准考证号占位
      const examId = 'AUTO' + Date.now();
      const scores = generateScores();
      const ins = await pool.query(
        `INSERT INTO students (name, exam_id, school, scores, auto_generated, generated_at)
         VALUES ($1, $2, $3, $4, true, now()) RETURNING *`,
        [name.trim(), examId, '浙江省教育考试院', JSON.stringify(scores)]
      );
      console.log(`[自动生成] ${name.trim()}`);
      send(res, 200, { success: true, student: rowToStudent(ins.rows[0]) });
    } catch (e) {
      console.error('query error:', e.message);
      send(res, 500, { error: '数据库错误，请稍后重试' });
    }
    return;
  }

  // 后台：获取所有考生
  if (method === 'GET' && pathname === '/api/admin/students') {
    try {
      const { rows } = await pool.query('SELECT * FROM students ORDER BY id ASC');
      send(res, 200, { students: rows.map(rowToStudent), subjects: SUBJECTS, subjectRanges: SUBJECT_RANGES });
    } catch (e) { send(res, 500, { error: '数据库错误' }); }
    return;
  }

  // 后台：新增考生（只需姓名+分数，exam_id 自动生成）
  if (method === 'POST' && pathname === '/api/admin/students') {
    const { name, scores } = await readBody(req);
    if (!name) { send(res, 400, { error: '姓名为必填项' }); return; }
    try {
      const examId = 'MANUAL' + Date.now();
      const { rows } = await pool.query(
        `INSERT INTO students (name, exam_id, school, scores) VALUES ($1, $2, $3, $4) RETURNING *`,
        [name, examId, '浙江省教育考试院', JSON.stringify(scores || {})]
      );
      send(res, 201, { success: true, student: rowToStudent(rows[0]) });
    } catch (e) {
      console.error('insert error:', e.message); send(res, 500, { error: '数据库错误' });
    }
    return;
  }

  // 后台：更新考生（只允许改姓名和分数）
  if (method === 'PUT' && pathname.startsWith('/api/admin/students/')) {
    const id = parseInt(pathname.split('/').pop());
    const body = await readBody(req);
    try {
      const { rows } = await pool.query(
        `UPDATE students SET
           name   = COALESCE($1, name),
           scores = COALESCE($2, scores),
           auto_generated = false,
           updated_at = now()
         WHERE id = $3 RETURNING *`,
        [body.name || null, body.scores ? JSON.stringify(body.scores) : null, id]
      );
      if (!rows.length) { send(res, 404, { error: '考生不存在' }); return; }
      send(res, 200, { success: true, student: rowToStudent(rows[0]) });
    } catch (e) {
      console.error('update error:', e.message); send(res, 500, { error: '数据库错误' });
    }
    return;
  }

  // 后台：删除考生
  if (method === 'DELETE' && pathname.startsWith('/api/admin/students/')) {
    const id = parseInt(pathname.split('/').pop());
    try {
      const { rowCount } = await pool.query('DELETE FROM students WHERE id = $1', [id]);
      if (!rowCount) { send(res, 404, { error: '考生不存在' }); return; }
      send(res, 200, { success: true });
    } catch (e) {
      console.error('delete error:', e.message); send(res, 500, { error: '数据库错误' });
    }
    return;
  }

  if (method === 'GET' && pathname === '/api/admin/preview-scores') {
    send(res, 200, { scores: generateScores() }); return;
  }

  res.writeHead(404); res.end('Not found');
});

const PORT = process.env.PORT || 3000;
async function start() {
  try { await pool.query('SELECT 1'); console.log('✅ 数据库连接成功'); }
  catch (e) { console.error('❌ 数据库连接失败:', e.message); process.exit(1); }
  server.listen(PORT, () => console.log(`✅ 服务启动 port ${PORT}`));
}
start();
